# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fcc93972ef6bcd418ff24e70a476f22690131bbd19153bf1a45d7ccd13f492c9160e5be381f955a24f5142bde69c9bc5b2f49f82cad40c1ffc6a3e5e303180b

test:
  secret_key_base: 718460b6372bdf8a48c2e7ab95a2e22d8957a28b8f1bad07182c56f749764e4dcf0d0316364dc151845f27a2175e3c3dc1c7ef6eb212ba60c5dbea10643ec948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
